version: '3.8'
services:
  node:
    image: ghcr.io/canarynetwork/prysm-beacon-chain:v2.0.0rc1-unstable2
    command: |
      --accept-terms-of-use
      --contract-deployment-block $DEPLOYMENT_BLOCK
      --http-web3provider $XDAI_RPC_URL
      --bootstrap-node /root/sbc/config/bootnodes.yaml
      --config-file /root/sbc/config/config.yml
      --chain-config-file /root/sbc/config/config.yml
      --rpc-host 0.0.0.0
      --p2p-local-ip 0.0.0.0
      --p2p-host-ip $PUBLIC_IP
      --subscribe-all-subnets
      --monitoring-host 0.0.0.0
      --verbosity $LOG_LEVEL
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '127.0.0.1:4000:4000'
      - '127.0.0.1:3500:3500'
      - '127.0.0.1:8080:8080'
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  validator-import:
    image: ghcr.io/canarynetwork/prysm-validator:v2.0.0rc1-unstable2
    command: |
      accounts import
      --accept-terms-of-use
      --keys-dir /root/sbc/keys/validator_keys
      --account-password-file /root/sbc/keys/keystore_password.txt
      --wallet-password-file /root/sbc/keys/wallet_password.txt
    volumes:
      - ./keys:/root/sbc/keys
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
  validator-list:
    image: ghcr.io/canarynetwork/prysm-validator:v2.0.0rc1-unstable2
    command: |
      accounts list
      --accept-terms-of-use
      --wallet-password-file /root/sbc/keys/wallet_password.txt
    volumes:
      - ./keys:/root/sbc/keys
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
  validator:
    image: ghcr.io/canarynetwork/prysm-validator:v2.0.0rc1-unstable2
    command: |
      --accept-terms-of-use
      --config-file /root/sbc/config/config.yml
      --chain-config-file /root/sbc/config/config.yml
      --wallet-password-file /root/sbc/keys/wallet_password.txt
      --beacon-rpc-provider node:4000
    volumes:
      - ./config:/root/sbc/config
      - ./keys:/root/sbc/keys
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }

